name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.1.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          mkdir artifacts
        name: Create Artifacts Directory

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
   
      - name: Install Workloads
        run: dotnet workload install ios maccatalyst

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Build NukeProxy Native Library
        run: sh build.sh

      - name: Build Binding Library
        run: dotnet build src/ImageCaching.Nuke/ImageCaching.Nuke.csproj /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.semVer }} /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}

      - name: Upload a Other Artifacts
        if: always()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Other
          path: 'artifacts/**/*'

      - name: Upload a NuGet Artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: NuGet
          path: '**/*.nupkg'
